name: CD using argocd

on:
    push:
        tags:
          - "*.*.*"

env:
    IMAGE: ${{ vars.NCR_REGISTRY }}/lion-app
    IMAGE_TAG: ${{ vars.NCR_REGISTRY }}/lion-app:latest

jobs:
    deploy:
      name: deploy the new version
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Helm repository
          uses: actions/checkout@v3
          with:
            repository: Ex-ez/lion_infra
            ref: main
            token: ${{ secrets.PAT }}

        - name: Update version tag
          run: |
            sed -ie 's/appVersion: ".*"/appVersion: "'${{ github.event.release.tag_name }}'"/g' helm-chart/charts/Chart.yaml

        - name: Commit files
          run: |
            git config --local user.email "khkkor3@naver.com"
            git config --local user.name "github-actions[bot]"
            git commit -a -m "update tag"

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            repository: Ex-ez/lion_infra
            branch: main            
